name: CI

on: pull_request

jobs:
  merge-dependabot:
    name: Merge dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v1.8.134
        with:
          GITHUB_LOGIN: dependabot[bot]
          # This must be used as GitHub Actions token does not support
          # pushing to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bump-package-version:
    if: github.actor == 'dependabot[bot]'
    name: Bumps as a patch
    needs:
      - merge-dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: phips28/gh-action-bump-version@v8.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'master'